development:
  adapter: postgresql
  database: suportRoo_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: suportRoo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: suportRoo_production
  pool: 5
  timeout: 5000
